settings:
  title: 'Online Judge Status'
  url: 'https://oj-status.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: luogu # unique identifier
    name: Luogu
    url: 'https://www.luogu.com.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true

  - id: codeforces
    name: CodeForces
    url: 'https://codeforces.com/'
    method: GET
    expectStatus: 200

  - id: atcoder
    name: AtCoder
    url: 'https://atcoder.jp/'
    method: GET
    expectStatus: 200

  - id: spoj
    name: SPOJ
    url: 'https://www.spoj.com/'
    method: GET
    expectStatus: 200

  - id: uva
    name: UVa Online Judge
    url: 'https://onlinejudge.org/'
    method: GET
    expectStatus: 200
    
  - id: libreoj
    name: LibreOJ
    url: 'https://loj.ac'
    method: GET
    expectStatus: 200
    
  - id: acwing
    name: AcWing
    url: 'https://www.acwing.com/'
    method: GET
    expectStatus: 200
    
  - id: hydro
    name: HydroOJ
    url: 'https://hydro.ac/'
    method: GET
    expectStatus: 200
    
  - id: vjudge
    name: Virtual Judge
    url: 'https://vjudge.net/'
    method: GET
    expectStatus: 200
    
  - id: poj
    name: PKU JudgeOnline
    url: 'http://poj.org/'
    method: GET
    expectStatus: 200
    
  - id: vijos
    name: Vijos
    url: 'https://vijos.org/'
    method: GET
    expectStatus: 200
    
  - id: darkbzoj
    name: DarkBZOJ
    url: 'https://darkbzoj.cc/'
    method: GET
    expectStatus: 200
